# Generated by Django 5.1.7 on 2025-03-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('nationality', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='estate.client')),
            ],
            options={
                'verbose_name': 'Client Comment',
                'verbose_name_plural': 'Client Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_offers', to='estate.client')),
            ],
            options={
                'verbose_name': 'Client Offer',
                'verbose_name_plural': 'Client Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOfferComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='estate.clientoffer')),
            ],
            options={
                'verbose_name': 'Client Offer Comment',
                'verbose_name_plural': 'Client Offer Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('address_text', models.CharField(blank=True, max_length=200, null=True)),
                ('ulica', models.CharField(blank=True, max_length=200, null=True)),
                ('numer_budynku', models.CharField(blank=True, max_length=20, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10, null=True)),
                ('dzielnica', models.CharField(blank=True, max_length=200, null=True)),
                ('województwo', models.CharField(max_length=200)),
                ('powiat', models.CharField(max_length=200)),
                ('gmina', models.CharField(max_length=200)),
                ('miejscowość', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('deposit_price', models.FloatField(blank=True, null=True)),
                ('deposit_duration', models.FloatField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('room', 'Room'), ('sale', 'Sale'), ('office', 'Office'), ('apartment', 'Apartment'), ('garage', 'Garage'), ('land', 'Land'), ('villa', 'Villa'), ('warehouse', 'Warehouse'), ('local', 'Local'), ('other', 'Other')], default='other', max_length=20)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('average', 'Average'), ('excellent', 'Excellent'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('clients', models.ManyToManyField(blank=True, related_name='offers', through='estate.ClientOffer', to='estate.client')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-active', '-price'],
            },
        ),
        migrations.AddField(
            model_name='clientoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_offers', to='estate.offer'),
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.offer')),
            ],
            options={
                'verbose_name': 'Offer Image',
                'verbose_name_plural': 'Offer Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
