# Generated by Django 5.1.7 on 2025-03-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='gmina',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='miejscowość',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='powiat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='województwo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
