# Generated by Django 5.1.7 on 2025-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_offer_gmina_alter_offer_miejscowość_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
