# Generated by Django 5.1.7 on 2025-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_client_passport_expiry_date_client_passport_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
