# Generated by Django 5.1.7 on 2025-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_client_passport_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_serial',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
