# Generated by Django 5.1.7 on 2025-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_alter_client_passport_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
