# Generated by Django 5.1.7 on 2025-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_alter_client_passport_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
