# Generated by Django 5.1.7 on 2025-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_alter_client_passport_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
