# Generated by Django 5.1.7 on 2025-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_client_contract_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the contract', max_length=200)),
                ('file', models.FileField(help_text='Upload a PDF file', upload_to='default_contracts/')),
            ],
            options={
                'verbose_name': 'Default Contract',
                'verbose_name_plural': 'Default Contracts',
            },
        ),
    ]
