# Generated by Django 5.1.7 on 2025-04-01 10:38

import estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_defaultcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(upload_to=estate.models.rename_offer_image),
        ),
    ]
