# Generated by Django 5.1.7 on 2025-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_alter_offerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_serial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
