# Generated by Django 5.1.7 on 2025-04-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_alter_client_passport_serial_alter_offer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
